name: '@react-barcode-scanner/hooks'

on:
  release:
    types: [created]

#on:
#  push:
#    branches:
#      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 23
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: npx rollup -c
      - run: npm pack
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
